openapi: 3.0.0
info:
  title: promptic Cleanup Contract
  description: |
    Contract defining the public API after code cleanup. This contract verifies
    that only the expected functions are exported and removed functions cannot be imported.
  version: 1.0.0

paths:
  /public-api:
    get:
      summary: Get public API exports
      description: |
        Verifies that promptic.__init__.py exports only the expected functions:
        - load_prompt
        - export_version
        - cleanup_exported_version
        - __version__
      responses:
        '200':
          description: Public API contains only expected exports
          content:
            application/json:
              schema:
                type: object
                properties:
                  exports:
                    type: array
                    items:
                      type: string
                    example: ["load_prompt", "export_version", "cleanup_exported_version", "__version__"]
                  removed_exports:
                    type: array
                    items:
                      type: string
                    example: ["bootstrap_runtime", "load_blueprint", "preview_blueprint", "render_for_llm", "render_instruction", "render_preview"]

  /import-errors:
    get:
      summary: Verify removed modules cannot be imported
      description: |
        Verifies that attempting to import removed modules raises ImportError.
        This is a contract test to ensure cleanup was successful.
      responses:
        '200':
          description: All removed modules raise ImportError as expected
          content:
            application/json:
              schema:
                type: object
                properties:
                  removed_modules:
                    type: array
                    items:
                      type: object
                      properties:
                        module:
                          type: string
                        raises_import_error:
                          type: boolean
                    example:
                      - module: "promptic.blueprints"
                        raises_import_error: true
                      - module: "promptic.adapters"
                        raises_import_error: true
                      - module: "promptic.token_counting"
                        raises_import_error: true
                      - module: "promptic.settings"
                        raises_import_error: true

  /examples:
    get:
      summary: Verify examples 003-006 work after cleanup
      description: |
        Verifies that all examples continue to work after code cleanup.
        Examples must run without errors and produce expected output.
      responses:
        '200':
          description: All examples work correctly
          content:
            application/json:
              schema:
                type: object
                properties:
                  examples:
                    type: array
                    items:
                      type: object
                      properties:
                        example_id:
                          type: string
                        status:
                          type: string
                          enum: ["pass", "fail"]
                        output_length:
                          type: integer
                    example:
                      - example_id: "003-multiple-files"
                        status: "pass"
                        output_length: 500
                      - example_id: "004-file-formats"
                        status: "pass"
                        output_length: 300
                      - example_id: "005-versioning"
                        status: "pass"
                        output_length: 200
                      - example_id: "006-version-export"
                        status: "pass"
                        output_length: 1000

components:
  schemas:
    PublicAPI:
      type: object
      properties:
        load_prompt:
          type: function
          description: Load a versioned prompt from a directory
        export_version:
          type: function
          description: Export a specific version of a prompt structure
        cleanup_exported_version:
          type: function
          description: Clean up exported version directory
        __version__:
          type: string
          description: Library version string

    RemovedAPI:
      type: object
      properties:
        bootstrap_runtime:
          type: function
          status: removed
        load_blueprint:
          type: function
          status: removed
        preview_blueprint:
          type: function
          status: removed
        render_for_llm:
          type: function
          status: removed
        render_instruction:
          type: function
          status: removed
        render_preview:
          type: function
          status: removed

